# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod download
#     # you may remove this if you don't need go generate
#     - go generate ./...
project_name: vault-token-helper
# release:
#   draft: true
builds:
  - binary: vault-token-helper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
